name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: 'poc-dev-433917'

      - name: 'Docker auth'
        run: |-
          gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: 'Build and push container'
        run: |-
          docker build -t "europe-central2-docker.pkg.dev/poc-dev-433917/logger-app/logger-app:${{ github.sha }}"
          docker push "europe-central2-docker.pkg.dev/poc-dev-433917/logger-app/logger-app:${{ github.sha }}"
